name: Deploy React app to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the 'main' branch
    paths-ignore:
      - 'gh-pages/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Match your node version

      # Cache node_modules to speed up build
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install -g npm@10.9.0
          npm install -g serve
          npm install

      # Build the React app
      - name: Build React app
        run: |
          npm run build
      - name: Set Git configuration
        run: |
          git config --global user.name "popeyeight"
          git config --global user.email "popeyeight@gmail.com"  # Replace with your email
      # Ensure these Git configurations are correct for automated commits
      - name: Deploy to GitHub Pages
        run: |
          npx gh-pages -d build -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/popeyeight/popeyeight.github.io.git
        env:
          #GH_TOKEN: ${{ secrets.neon_monkey_secret }}  # Ensure this is passed from your secrets
          github_token: ${{ secrets.GITHUB_TOKEN }}
