name: Deploy Django to GitHub Pages

on:
  push:
    branches:
      - main  # Change if using a different branch
    paths-ignore:
      - 'gh-pages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Static Files
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          python manage.py collectstatic --noinput
          mv staticfiles public  # Move to public folder for GitHub Pages

      # Ensure these Git configurations are correct for automated commits
      # - name: Git Commit
      #   run: |
      #     git config --global user.name "nprtvx"
      #     git config --global user.email "neonmonkey08@gmail.com"
      #     git remote set-url origin https://x-access-token:${{ secrets.DJANGO_TOKEN }}@github.com/nprtvx/nprtvx.github.io.git
      #     git checkout --orphan gh-pages
      #     git add -A
      #     git commit -m "Deploy static files"
      #     git push -f origin gh-pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.DJANGO_TOKEN }}
          branch: gh-pages
          folder: public  # Static files directory
