name: Deploy Django to GitHub Pages

permissions:
  contents: write  # Grants write permission to the contents

on:
  push:
    branches:
      - main  # Change if using a different branch
    paths-ignore:
      - 'gh-pages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Static Files
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          python manage.py collectstatic --noinput
          echo "Contents of staticfiles directory:"
          ls -la staticfiles  # List contents of staticfiles directory for debugging
          mv staticfiles public  # Move to public folder for GitHub Pages
          echo "Contents of public directory:"
          ls -la public  # List contents of public directory for debugging

      - name: Deploy to GitHub Pages
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # uses: JamesIves/github-pages-deploy-action@v4
        # with:
        #   github_token: ${{ secrets.DJANGO_TOKEN }}
        #   branch: gh-pages
        #   folder: public  # Static files directory
