name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set to the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the project
      run: |
        # Add your build commands here
        echo "Building the project..."

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DJANGO_TOKEN }}
        publish_dir: ./public  # Set to the directory you want to publish